import path from 'path';

/**
 * knex file for connection route, migration (Creating tables on data base),
 * and seeds(Default values inserted on DB before starting the server for the first time).
 */

module.exports = {
    client: 'sqlite3',
    connection: {
        filename: path.resolve(__dirname, 'src', 'database', 'database.sqlite')
    },
    migrations: {
       directory: path.resolve(__dirname, 'src', 'database', 'migrations')
    },
    seeds :{
        directory: path.resolve(__dirname, 'src', 'database', 'seeds')
    },
    useNullAsDefault: true, // this was added because of a warning generated by sqlite.
}
